//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Programm = new HashSet<Programm>();
            this.Training = new HashSet<Training>();
        }
    
        public int PlanId { get; set; }
        public Nullable<int> BenutzerId { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual ICollection<Programm> Programm { get; set; }
        public virtual ICollection<Training> Training { get; set; }
    }
}
