//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thema
    {
        public Thema()
        {
            this.Uebung = new HashSet<Uebung>();
        }
    
        public int ThemaId { get; set; }
        public string Name { get; set; }
        public Nullable<int> VerzeichnisId { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> TrainingsartId { get; set; }
    
        public virtual ICollection<Uebung> Uebung { get; set; }
    }
}
