//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uebung
    {
        public Uebung()
        {
            this.Programm = new HashSet<Programm>();
        }
    
        public int UebungId { get; set; }
        public string Name { get; set; }
        public string Beschreibung { get; set; }
        public string Bildpfad { get; set; }
        public int Stufe { get; set; }
        public Nullable<int> StdWiederholung { get; set; }
        public Nullable<int> StdDauer { get; set; }
        public int ThemaId { get; set; }
    
        public virtual ICollection<Programm> Programm { get; set; }
        public virtual Thema Thema { get; set; }
    }
}
